### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(QT_Calculator_App)
add_subdirectory(QT_Calculator_AppContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    QT_Calculator_Appplugin
    QT_Calculator_AppContentplugin
    QtQuickDesignerComponents)